# Generated by Django 4.2.3 on 2023-07-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='razore_pay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='razore_pay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='razore_pay_payment_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
