# Generated by Django 4.2.3 on 2023-07-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sizevariant_product_size_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_of_products',
            field=models.IntegerField(default=0),
        ),
    ]
