# Generated by Django 4.2.3 on 2023-07-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_no_of_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender_category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
