# Generated by Django 4.2.3 on 2023-07-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_gender_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariant',
            name='size_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
