# Generated by Django 4.2.3 on 2023-07-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_sizevariant_size_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizevariant',
            name='type_of_size',
        ),
    ]
