# Generated by Django 4.2.3 on 2023-07-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_sizevariant_type_of_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
