# Generated by Django 4.2.3 on 2023-07-26 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_price_category_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_code', models.CharField(max_length=20)),
                ('is_expired', models.BooleanField(default=False)),
                ('discounted_price', models.IntegerField(default=100)),
                ('minimun_amount', models.IntegerField(default=1500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
