# Generated by Django 4.2.3 on 2023-07-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discounted_price',
            field=models.IntegerField(default=200),
        ),
    ]
